# Generated by Django 4.0.6 on 2022-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('message_text', models.CharField(max_length=1024)),
                ('mobile_code', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('time_end', models.DateTimeField()),
            ],
        ),
    ]
