# Generated by Django 4.0.6 on 2022-07-31 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mobile_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
